### ISSUE TITLE
Disscussion panel

### ISSUE THREAD

**Issue by chrismatheson** [mancjs/mancjs.github.io#4]
### Is tooling hurting us ?

Nowadays there are 300 frameworks, 27 task runners, 46 compile to JS languages, linters, optimisers, css preprocessors, responsive image creators. Do we need all of this? Is it a good thing or a bad thing?

### Is full stack JS a benefit?

Does choosing best language for the job bring more benefits than choosing a language everyone knows? Is there a reason why full stack JS is better than using a mix of other technologies?

### Typing

Should we be encouraging tools and language features that bring in typing or type hints?

**Comment by martinrue** [comment]
Event details (finally) live: http://mancjs.com/#panel-debate
